language: python

python:
     - "3.5"

install:
     pip install -r requirements.txt

script:
     - python -m unittest -v tests/*.py

deploy:
     provider: heroku
     api_key: ae17aaf9-cef2-44c3-b80f-c7a2594b26a0
     app: rsoi-lab1-simple-server
