language: python

python:
     - "3.6"

install:
     pip install -r requirements.txt

script:
     - python -m unittest -v tests/*.py

deploy:
     provider: heroku
     api_key: $KEY
     app: rsoi-server
